version: '3.4'

services:
  stripepayment:
    image: stripepayment
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 8080:8080
      - 443:443
      - 4242:4242
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "checkout.html"]
